apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.auth.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{ .Values.auth.realm.file.name }}.json: {{ tpl (.Files.Get "config/realm-export.json") . | quote }}
