apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # admin
  KEYCLOAK_ADMIN: YWRtaW4=
  # admin
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4= 
