apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.golangBack.name }}-clusterip
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.golangBack.components }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.golangBack.servicePort }}
    targetPort: {{ .Values.golangBack.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.golangBack.components }}
