apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gateway.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.gateway.components }}
  replicas: {{ .Values.gateway.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.gateway.components }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/krakend-gateway/krakend-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.gateway.name }}
        image: "{{ .Values.gateway.image }}:{{ .Values.gateway.version }}"
        ports:
        - containerPort: {{ .Values.gateway.containerPort }}
        resources:
          limits: {{ .Values.gateway.limits | toYaml | nindent 14 }}
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", {{ .Values.gateway.containerPort | quote }} ]
        readinessProbe:
          httpGet:
            path: /v1/nodejs/public
            port: {{ .Values.gateway.containerPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.gateway.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: config-volume
            mountPath: /etc/krakend/
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.gateway.name }}-configmap
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0