apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.libsql.name }}-clusterip
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.libsql.components }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.libsql.servicePort }}
    targetPort: {{ .Values.libsql.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.libsql.components }}
