apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.back.name }}-service-monitor
  namespace: default
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.back.components }}
  endpoints:
  - port: http-metrics
    interval: 10s
    path: /metrics