# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: infinite-calls
#   namespace: {{ .Values.namespace }}
#   labels:
#     app: infinite-calls
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: infinite-calls
#   template:
#     metadata:
#       name: infinite-calls
#       labels:
#         app: infinite-calls
#     spec:
#       containers:
#       - name: infinite-calls
#         image: busybox:1.28
#         command:
#         - /bin/sh
#         - -c
#         - "while true; do wget -q -O- http://grogu-back-clusterip:9070/ready; done"