apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}-clusterip
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.gateway.servicePort }}
    targetPort: {{ .Values.gateway.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Values.gateway.components }}
