apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-clusterip
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.postgres.components }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.postgres.components }}