kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.redis.name }}-clusterip
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.redis.components }}
spec:
  selector:
    app: {{ .Values.redis.components }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.containerPort }}
      protocol: TCP