apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.postgres.migration.name }}-{{ .Values.postgres.migration.version }}-job
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.migration.components }}
    spec:
      initContainers:
        {{- include "wait-for-postgres-db" . | indent 8}}
      containers:
      - name: {{ .Values.postgres.migration.name }}
        image: "{{ .Values.postgres.image }}:{{ .Values.postgres.version }}"
        command: ["sh", "-c"]
        args:
          - |
            psql -h $(POSTGRES_HOST) -U $(POSTGRES_USER) -d $(POSTGRES_DB) -f /mnt/sql/migration-{{ .Values.postgres.migration.version }}.sql
        env:
        - name: PGPASSWORD
          value: "$(POSTGRES_PASSWORD)"
        envFrom:
            - secretRef:
                name: {{ .Values.postgres.name }}-secret
        volumeMounts:
        - name: {{ .Values.postgres.migration.name }}-volume
          mountPath: /mnt/sql
      restartPolicy: Never
      volumes:
      - name: {{ .Values.postgres.migration.name }}-volume
        configMap:
          name: {{ .Values.postgres.migration.name }}-configmap
          items:
          - key: migration-{{ .Values.postgres.migration.version }}.sql
            path: migration-{{ .Values.postgres.migration.version }}.sql 
