apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.name | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  # "5432"
  # POSTGRES_PORT: NTQzMg==
  # POSTGRES_HOST: postgres-clusterip
  # POSTGRES_HOST: cG9zdGdyZXMtY2x1c3Rlcmlw
  # REDIS_HOST: redis-cache-clusterip
  REDIS_HOST: cmVkaXMtY2FjaGUtY2x1c3Rlcmlw
  # REDIS_PORT: "6379"
  REDIS_PORT: NjM3OQ==
