apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.database.name | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}

  # TODO: remove from secrets and use from values.yaml
  REDIS_HOST: cmVkaXMtY2FjaGUtY2x1c3Rlcmlw
  REDIS_PORT: NjM3OQ==
