apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nodejsBack.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.nodejsBack.components }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.nodejsBack.components }}
  replicas: {{ .Values.nodejsBack.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodejsBack.components }}
    spec:
      initContainers:
        {{- include "wait-for-postgres-db" . | indent 8}}
        {{- include "wait-for-redis-cache" . | indent 8}}
      containers:
      - name: {{ .Values.nodejsBack.name }}
        image: "{{ .Values.nodejsBack.image }}:{{ .Values.nodejsBack.version }}"
        ports:
        - containerPort: {{ .Values.nodejsBack.containerPort }}
        resources:
          limits: {{ .Values.nodejsBack.limits | toYaml | nindent 14 }}
        envFrom:
            - secretRef:
                name: {{ .Values.postgres.name }}-secret
        env:
        - name: PORT
          value: {{ .Values.nodejsBack.containerPort | quote }}
        - name: POSTGRES_PORT
          value: {{ .Values.postgres.servicePort | quote }}
        - name: POSTGRES_HOST
          value: "{{ .Values.postgres.name }}-clusterip"
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.nodejsBack.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
