{{- if .Values.backups.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backups.minio.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.backups.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.backups.minio.rootPassword | quote }}
{{- end }}
